name: Get My Leetcode Rank Value
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12,0 * * *'
permissions: write-all
jobs:
  extract-rank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install puppeteer

      - name: Get Rank value
        run: |
          node -e '
          const fs = require("fs");
          const puppeteer = require("puppeteer");

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto("https://leetcode.com/imacemarx", { waitUntil: "networkidle0" ,timeout: 60000 });
            const rankElement = await page.$(".ttext-label-1.dark\\:text-dark-label-1.font-medium");
            const rankValue = await rankElement.evaluate((el) => el.innerText);
            console.log("Rank:", rankValue);

            // Format the current date and time
            const currentDate = new Date();
            currentDate.setHours(currentDate.getHours() + 8);
            const year = currentDate.getFullYear();
            const month = (currentDate.getMonth() + 1).toString().padStart(2, '0');
            const day = currentDate.getDate().toString().padStart(2, '0');
            const hours = currentDate.getHours().toString().padStart(2, '0');
            const minutes = currentDate.getMinutes().toString().padStart(2, '0');
            const seconds = currentDate.getSeconds().toString().padStart(2, '0');
            const formattedDate = `${year}${month}${day}${hours}${minutes}${seconds}T0800`;
            console.log(formattedDate);

            // Read existing file contents
            let existingContent = "";
            try {
              existingContent = fs.readFileSync("myrank", "utf8");
            } catch (error) {
              console.log("No existing file found. Creating new file.");
              fs.writeFileSync("myrank", "");
            }

            // Update file with new rank value and current date
            const updatedContent = `${formattedDate}:${rankValue}\n${existingContent}`;
            fs.writeFileSync("myrank", updatedContent);

            await browser.close();
          })();
          '

      - name: Commit and push changes
        run: |
          git config --local user.email "imacemarx@gmail.com"
          git config --local user.name "imacemarx"
          git add myrank
          git commit -m "other: Update rank value"
          git push
